In [7]:
import numpy as np
import random
import pandas as pd
#Works
class linearRegression():
    def __init__(self,X,Y):
        #pass in the inputs to the function as well as the outputs
        self.X = X
        self.Y = Y
        self.XTil = np.insert(X.T,0,np.ones(X.shape[0]), axis = 0).T
        self.wTil = np.ones(X.shape[1]+1)
    def cost(self):
        #How far away we are from the actual solution
        #Though not particularly useful in this program it could be used later.
        g = 0
        for k in range(self.XTil.shape[0]):
            g+=(np.dot(self.XTil[0].T,self.wTil) - self.Y[k])**2
        return g
    def costPrime(self):
        #The derivitive of the cost function
        delG = np.zeros(self.wTil.size)
        for k in range(self.XTil.shape[0]):
            delG += np.dot(self.XTil[k],(np.dot(self.XTil[k].T,self.wTil) - self.Y[k]))
        delG = 2 * delG
        return delG
        
    
    
    
class gradientDecent():
    def __init__(self, learningRate, model, flatMin):
        #This will find a minimum on a function
        self.learningRate = learningRate
        self.model = model
        self.flatMin = flatMin
    def decent(self):
        #A single iteration of a step
        self.model.wTil -= self.model.costPrime()*self.learningRate
        
    def optimize(self):
        #decends until a minimum has been found
        while (self.model.costPrime().dot(self.model.costPrime())) > self.flatMin:
            self.decent()
        return self.model
    
    
# 1 = w0 + w1*1 + w2*2
# 2 = w0 + w1*3 + w2*4
# 5 = w0 + w1*9 + w2*11
# 8 = w0 + w1*13 + w2*2

X = np.array(([1,2],[3,4], [9,11], [13,2]))
Y = np.array(([1,2, 5, 8]))
LG = linearRegression(X, Y)
print(LG.cost())
print(LG.costPrime())
trainer = gradientDecent(.0001, LG, .001)
LG = trainer.optimize()
print(LG.cost())
print(LG.costPrime())
print(LG.wTil)

30.0
[  66.  538.  444.]
65.9146049641
[ 0.03148053 -0.00193169 -0.00228943]
[ 0.5707454   0.58309198 -0.07513857]


In [27]:
a = np.array([1,2,3])
print(a.dot(a))
print(np.dot(a,a))

14
14


In [5]:
X = np.array(([1,2],[3,4], [9,11], [13,2]))
Y = np.array(([1,2, 5, 8]))
XTil = np.insert(X.T,0,np.ones(X.shape[0]), axis = 0).T
wTil = np.ones(X.shape[1]+1)
print(X)
print(XTil)

[[ 1  2]
 [ 3  4]
 [ 9 11]
 [13  2]]
[[ 1  1  2]
 [ 1  3  4]
 [ 1  9 11]
 [ 1 13  2]]
